<<<<<<< HEAD
server:
  port: 1113


#mybatis
#mybatis-plus:
#  mapper-locations: classpath:com/chinacaring/patient/dao/mapper/xml/*Mapper.xml
##  mapper-locations: classpath:/mapper/*Mapper.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.chinacaring.patient.dao.entity
#  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 2
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 2
#    #驼峰下划线转换
#    db-column-underline: true
#    #刷新mapper 调试神器
#    refresh-mapper: true
#    #数据库大写下划线转换
#    #capital-mode: true
#    #序列接口实现类配置
#    #key-generator: com.baomidou.springboot.xxx
#    #逻辑删除配置
#    #logic-delete-value: 0
#    #logic-not-delete-value: 1
#    #自定义填充策略接口实现
#    #meta-object-handler: com.baomidou.springboot.xxx
#    #自定义SQL注入器
#    #sql-injector: com.baomidou.springboot.xxx
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: true

spring:
  datasource:

    url: jdbc:mysql://192.168.1.161/public_version_model
    username: root
    password: chinacaring
    driver-class-name: com.mysql.jdbc.Driver

    primary:
      url: jdbc:mysql://101.132.74.234/test1
      username: root
      password: chinacaring
      driver-class-name: com.mysql.jdbc.Driver

    secondary:
      url: jdbc:mysql://101.132.74.234/test1
      username: root
      password: chinacaring
      driver-class-name: com.mysql.jdbc.Driver



#jpa模式配置 以及 设置打印sql语句
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true


  redis:
    database: 0
    host: 101.132.74.234
    port: 6379
    password: mima
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0


sms:
  ip: 202.102.41.101
  port: 9005
  username: 025C00359449
  password: zdyy@83272000
=======
#server:
#  port: 1113
#
#
#spring:
#  datasource:
#    url: jdbc:mysql://101.132.74.234/test1
#    username: root
#    password: chinacaring
#    driver-class-name: com.mysql.jdbc.Driver
#
#    primary:
#      url: jdbc:mysql://101.132.74.234/test
#      username: root
#      password: chinacaring
#      driver-class-name: com.mysql.jdbc.Driver
#
#    secondary:
#      url: jdbc:mysql://101.132.74.234/test1
#      username: root
#      password: chinacaring
#      driver-class-name: com.mysql.jdbc.Driver
#
#  jpa:
#    properties:
#      hi
#
#
##jpa hibernate 模式配置
##spring.jpa.properties.hibernate.hbm2ddl.auto=update
##配置打印sql语句
#spring.jpa.properties.hibernate.show_sql=true
#
## REDIS (RedisProperties)
## Redis 数据库索引
#spring.redis.database=0
#
#spring.redis.host=101.132.74.234
##spring.redis.host=172.17.10.17
#
#spring.redis.port=6379
#
##spring.redis.password=
#spring.redis.password=mima233
#
#spring.redis.pool.max-active=8
#
#spring.redis.pool.max-wait=-1
#
#spring.redis.pool.max-idle=8
#
#spring.redis.pool.min-idle=0
#
#spring.redis.timeout=0
>>>>>>> 0411252277c8d7b436b0b013c019b7b56a227366
