spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ${mysql.username:root}
    password: ${mysql.password:FanDong}
    url: jdbc:mysql://${mysql.host:127.0.0.1}:${mysql.port:3306}/flowable?characterEncoding=utf8

server:
  port: 3333